---
include:
  - board: eyelash_sofle_left
    shield: nice_view
  - board: eyelash_sofle_right
    shield: nice_view
  - board: eyelash_sofle_right
    shield: nice_view_adapter nice_view_battery
    artifact-name: nice_view_battery_right
  - board: eyelash_sofle_left
    shield: nice_view_adapter nice_view_battery
    artifact-name: nice_view_battery_left
  - board: eyelash_sofle_left
    shield: settings_reset
